### ISSUE TITLE
Consider align all if no count given

### ISSUE THREAD

**Issue by azure-satellite** [tommcdo/vim-lion#13]
It's easy to align only the first occurrence: `1gl<motion>`. It is not possible, however, to align all occurrences unless you know how many there are

**Comment by tommcdo** [comment]
It looks like I've been [planning to do this](https://github.com/tommcdo/vim-lion/blob/903d4ccf2318dbbba45a3bf811110b57e095cdbd/plugin/lion.vim#L65) for a while (though the code around it seems a little shaky). I wasn't sure of an interface to make it happen, but I think I like the idea of using the absence of a count to align all.

I'll definitely look into this and see what I can come up with :+1:

**Comment by azure-satellite** [comment]
Awesome stuff. Thank you!
