### ISSUE TITLE
Trim excess spaces

### ISSUE THREAD

**Issue by sudo-nice** [tommcdo/vim-lion#15]
Given an aligned example:

```
$i        = 5;
$username = 'tommcdo';
$stuff    = array(1, 2, 3);
```

Do some rafactoring resulted in:

```
$i        = 5;
$user = 'tommcdo';
$stuff    = array(1, 2, 3);
```

Press `glip=` with result:

```
$i        = 5;
$user     = 'tommcdo';
$stuff    = array(1, 2, 3);
```

Expectation:

```
$i     = 5;
$user  = 'tommcdo';
$stuff = array(1, 2, 3);
```

What do you think?

**Comment by tommcdo** [comment]
I think it's a good idea, and I've felt that pain, but I think it's also a hard problem to get right without making style assumptions.

Right now, lion isn't very opinionated, which I find to be a good quality in a Vim operator. It doesn't format or tabularize your code; it just aligns by a character.

Let's discuss some possible use cases and see if we can come up with a good set of rules.

Take the actual outcome (the current behavior) from your example. What if we did `glip=` on that? Everything's already aligned, but each line has more than one space before the `=` sign. Should it be squashed to have a minimum of one space? Maybe some people would prefer it to have no spaces.

**Comment by sudo-nice** [comment]
> Maybe some people would prefer it to have no spaces.

I can't argue with that.

**Comment by jonahx** [comment]
Hi Tom,

I like your philosophy (and think this is an _excellently_ designed plugin).  I think you could accomodate this without sacrificing anything by making it an opt-in feature via a config variable.  I think the standard use-case isn't actually that tricky: You want the minimum possible space, plus one.  Of course you could go even further and make the "plus X" configurable, and probably add even more sub-configuration options, but I think the rule I suggested takes care of 90% of the use cases.

**Comment by jwmann** [comment]
Came to ask about this exact use-case.

```vim
set hlsearch           " Highlight search terms
set incsearch          " Find as you type search
set ignorecase           " Ignore case when search
set smartcase          " ...unless there's a capital letter in the query
```

Performing `glip"` will bring all comments to align with `ignorecase` instead of bringing `ignorecase` to the same alignment of the rest.

vim-lion seems to work great for things that aren't aligned yet but fails when alignment already exists. Not sure what the solution for this is though.

**Comment by qstrahl** [comment]
You might find [these lines from my config] (https://github.com/qstrahl/.vim/blob/b69faefef5bbf54f4df5b087ae158edce04e7273/init.vim#L239-L241) helpful

**Comment by sudo-nice** [comment]
Reopen, as it seems rather quick than dead.

**Comment by jwmann** [comment]
Maybe there should be an equivalent operator like `grip"` and `gRip"`. `r` for 're-align'.
It would basically strip the spaces like what @qstrahl's mapping does before aligning again.
That way it won't take away the simplicity of aligning things regularly. 

I don't know, just shootin out ideas.

**Comment by sudo-nice** [comment]
I'm for an option via config variable:
1. I (personally) never need to keep extra spaces on align, so there is no need to remember new combo (for me).
2. <kbd>gr</kbd> is already used by https://github.com/vim-scripts/ReplaceWithRegister. Sure, there could be any other combo, but see p.1 :smile:

**Comment by tommcdo** [comment]
I'm in favor of a configuration based approach, too. Defining more mappings is kinda greedy. I like @qstrahl's idea of allowing the setting to be buffer-local, so it can be configured by file type.

I'm kind of strapped for time lately, but I would love to review a pull request if anyone is up for it ☺️
