### ISSUE TITLE
Allow the command to operate on a selected region.

### ISSUE THREAD

**Issue by dncnmcdougall** [tommcdo/vim-lion#19]
This plug-in looks great.
It would be nice if this could operate on the selected region.

**Comment by edkolev** [comment]
The plugin works in visual mode - select the region, then `gl,` (assuming you want to align on `,`). 

This behaviour is in-line with other vim operators: `operator text-object` or `visual-selection operator`

**Comment by dncnmcdougall** [comment]
Right, yes. I retested and evidently I was wrong. Excellent.
