### ISSUE TITLE
gL is broken

### ISSUE THREAD

**Issue by chocolateboy** [tommcdo/vim-lion#23]
OS: Linux (Arch)
Vim: 8.0; included patches: 1-1127
vim-lion: 80de27aa2849b42d8f9cec6ac362858651677d95

Something in the [latest commit](https://github.com/tommcdo/vim-lion/commit/80de27aa2849b42d8f9cec6ac362858651677d95) has broken `gL` for me.

### Input

```json
{
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11
}
```

Action (with the cursor inside the curly brackets): `gLi{:`

### Before (08d5e714e87305c4b42f17db373af8244293e423)

```json
{
    "eight":  8,
    "nine":   9,
    "ten":    10,
    "eleven": 11
}
```

### After (https://github.com/tommcdo/vim-lion/commit/80de27aa2849b42d8f9cec6ac362858651677d95)

```json
{
    "eight" : 8,
    "nine"  : 9,
    "ten"   : 10,
    "eleven": 11
}
```

I have `g:lion_squeeze_spaces` set to 1, but I get the same result with it set to 0, or not set. Ditto `b:lion_squeeze_spaces`.

Likewise, I get the same result if `ignorecase` is enabled, disabled, or not set. Ditto `smartcase`.

I've tested and reproduced the issue with a minimal `$VIMRC`:

```vim
set nocompatible
call plug#begin('~/.vim/plugins')
Plug 'tommcdo/vim-lion'
call plug#end()
```

**Comment by tommcdo** [comment]
I merged in #25 (manually). I think that should fix this.
