### ISSUE TITLE
Use in a mapping

### ISSUE THREAD

**Issue by Jab2870** [tommcdo/vim-lion#29]
I would like to set up a mapping to do default alignments based on file type etc.

Initially I am adding this in my vimrc to get a minimal working example but even this isn't working.

```vimrc
vnoremap <leader>: gL:
```

Is there something I should be doing?

I would expect this to add spaces after the colon on the selection in visual mode. Typing `gL:` manually works.

**Comment by tommcdo** [comment]
Since you're using `:vnoremap`, Vim is not applying any other mappings and using the vanilla meaning of `gL:` (which I'm guessing is equivalent to simply typing `:`).

This should work if you use `:vmap` instead.

**Comment by Jab2870** [comment]
Thanks very much. That has fixed it
