### ISSUE TITLE
Are left and right swapped?

### ISSUE THREAD

**Issue by blasco** [tommcdo/vim-lion#31]
I have the following configuration:

```
" ---------------
" Vim-lion
" ---------------
let g:lion_create_maps=0
let g:lion_squeeze_spaces=1
nmap gfl <plug>LionLeft
nmap gfr <plug>LionRight
```
This:

"asdf,asdf,asdf = asdf
"asdf,asdf, asdf,asdf = asdf

Turns into this when I do: gflip= (go format left in paragraph =) 

"asdf,asdf,asdf =       asdf
"asdf,asdf, asdf,asdf = asdf

The spaces are added to the right of the =
Shouldn't the be added to the left or am I mistaking the concept of LionLeft?

**Comment by tommcdo** [comment]
I can see that being an easy misinterpretation to make. Actually, left and right refer to where the alignment character is relative to the spaces. Another way to think of it: With LionLeft, the alignment characters stay on the left; with LionRight, the alignment characters move to the right.

Admittedly, these names aren't very clear,  but I can't think of anything better at the moment.
